# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rathodpratik
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: portfolio
service: my-portfolio

provider:
  name: aws
  memorySize : 2048
  runtime: nodejs20.x # or the latest version you want to use
  region: ap-south-1 # Mumbai, India

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
